<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_5._1_Session</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LSEG.Data" Version="2.2.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="lseg-data.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
