<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_2._2._05_Pricing_StreamingEvents</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LSEG.Data.Content" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Configuration\Configuration.csproj" />
  </ItemGroup>

</Project>
